### ISSUE TITLE
get_avatar() gets incorrect pokemon.

### ISSUE THREAD

**Issue by aeroquil** [vsoch/pokemon#8]
`get_avatar()` seems to be getting the incorrect pokemon. here were just two examples i noticed.

![image](https://user-images.githubusercontent.com/29359463/92297799-f361a780-ef10-11ea-9ee0-471c8329350d.png)

It appears that the entire database has been mixed up, unless I'm misunderstanding.
I assume this was an error made in the `.json`?
Or am I doing something incorrectly?

Thanks!

**Comment by vsoch** [comment]
Oh I think it’s just a misunderstanding! The get avatar function returns a Pokémon avatar for you, based on your name (eg vsoch). If you want to catch a named Pokémon use the catch named function.

**Comment by aeroquil** [comment]
Ohhh, I'm sorry, thanks for clearing that up!

**Comment by vsoch** [comment]
No worries! You can use https://github.com/vsoch/pokemon/blob/2028d12efb5036adf617cef5a1db920f629ade8a/pokemon/master.py#L33 or skills.get_ascii.

**Comment by GeekApoorva** [comment]
Cool, thanks so much!

Also, would you mind if I used this in a bot I'm working on? The repository will be credited.

**Comment by vsoch** [comment]
That would be lovely! Please share with me when you finish, and I’ll spread the word!
